### ISSUE TITLE
Error due to GEOSisValidReason() returning NULL

### ISSUE THREAD

**Issue by imagico** [osmcode/osmcoastline#18]
I get `basic_string::_S_construct null not valid` - apparently due to GEOSisValidReason() unexpectedly returning NULL here:

https://github.com/osmcode/osmcoastline/blob/master/src/output_layers.cpp#L231

**Comment by joto** [comment]
@imagico can you check whether master fixes this for you?

The code around `GEOSisValidReason()` uses undocumented features of OGR and GEOS and is rather brittle. Some day we have to find a better way how to handle this.

**Comment by imagico** [comment]
Yes, it is fine now.  I did not check whether the fault is OGR or GEOS here.
