### ISSUE TITLE
Overlaps missing some coastline

### ISSUE THREAD

**Issue by stefda** [osmcode/osmcoastline#29]
It seems that if a coastline is not part of a water polygon, it won't be included to the added overlap. This affects areas with small islands that happen to be positioned in the overlap area (see pic below). Those islands are then completely or partially covered with the extra bit of generated polygon.

I am not sure if this is expected and if it's not, please advise on how to fix it (other than reducing the bbox overlap to 0).

![coastline-water-overlap-error](https://user-images.githubusercontent.com/212397/34203536-cb25ea0c-e57b-11e7-9e88-353d6d51c5af.png)

**Comment by joto** [comment]
Not sure what "t seems that if a coastline is not part of a water polygon," is supposed to mean. Can you post the command line you used and where in the world you are seeing this problem?

**Comment by stefda** [comment]
This particular snapshot is taken from QGIS with water polygons downloaded from openstreetmapsdata on 28/10/17. The location is roughly lat, lng = [36.771321, 24.411562]. I have recreated the same issue with running `osmcoastline_filter -o planet-filtered.osm.pbf planet-latest.osm.pbf` (on the planet file downloaded on 19/12/17) followed by `osmcoastline --output-lines --output-polygons=water -o coastline.osm.pbf planet-filtered.osm.pbf`.

What I meant was that if a water polygon doesn't include a specific coastline of a small island _before_ adding the overlap, it won't include if after adding the overlap either. I will try to explain better on the snapshot below. The added green line is where I think would've been the border between two water polygons without the bbox overlap. Notice than the water polygon to the left of the green line would not include the two small highlighted islets to the right of the green line. And, analogously, the water polygon to the right of the green line would not have the small highlighted islet that is to the right of the green line.

Adding the overlap doesn't seem to add the coastline of those islets to the extra overlapping area. _It seems_ that the overlap is simply added as a fully filled area in the place of those islets which results in the overlap covering the islets or showing "underneath" it, depending on the order of the rendering.

![coastline-water-overlap-error-explained](https://user-images.githubusercontent.com/212397/34207850-673472a0-e58c-11e7-8487-5592ffbacf25.png)

**Comment by stefda** [comment]
Possible a better demonstration of the effect below. I have coloured the two neighbouring water polygons differently, with a semi-transparent paint, to clearly show the overlap and how it covers the islets.

![water-overlaps-islets](https://user-images.githubusercontent.com/212397/34211914-e59d1a26-e59a-11e7-97ef-547eaf8b03ce.png)

**Comment by joto** [comment]
I agree that this is a bug. But I would argue it doesn't matter much because you are using too large an overlap if it does matter. The reason for the overlap is to avoid rendering artefacts at the seam between the tiles, so the overlap should be at most a pixel wide in whatever rendering you are using and then this wouldn't matter.

If this is an actual problem in your use case, maybe you can describe more why it is a problem for you.

**Comment by joto** [comment]
No further information. Closing.
