### ISSUE TITLE
successful testdata

### ISSUE THREAD

**Issue by kkdd** [osmcode/osmcoastline#34]
Hello,
Could you please supply a successful ```testdata```, too?

```console
$ ./runtest.sh 2>/dev/null; echo $?
There were 28 warnings.
There were 9 errors.
2
```

**Comment by joto** [comment]
There are valid test cases in `test/t`. The `testdata` isn't intended for automated testing, it is just a bunch of data helpful when developing.

**Comment by kkdd** [comment]
Thank you.
```test/t/valid-island-from-one-way.sh``` seems to have simple data.
