### ISSUE TITLE
Improve coastline check reports

### ISSUE THREAD

**Issue by liyinxiao** [osmcode/osmcoastline#38]
Now, osmcoastline program applies various checks to coastlines and adds problematic points/lines into Spatialite database as error_lines and error_points. This is slightly counter-intuitive if my goal is to find the problematic coastlines and fix them on live OSM - in which case, I would prefer way/node ids and their locations. So, I am interested in improving the coastline check reports, and making it easier to fix the issues flagged by osmcoastline. 

Here is an example of coastline check reports: 
- tagged as coastline: n8004639695
- missing node: n2414465027 from w859368258
- unconnected node: n2205490069 from w487040419
- intersection segments: (n2740259872 -> n2740259880), (n2740259887 -> n2740259876)
- overlap segments: (n8004629625 -> n8004629708), (n8004629625 -> n8004629708)
- invalid ring geometry: w2955146 Self-intersection at or near point 143.99311 49.969071100000001
- ring of this way is not marked as outer: w859838005
- wrong orientation: w859119484 at or near point 126.442 35.8159

_* Note, even if osmcoastline automatically fixes wrong orientation and turns polygons around, I would prefer to also fix these issues on live OSM._ 

One downside is it uses more memory - when I tested it with planet.pbf, it takes 12G of memory instead of 8G. 

Do you think this would be helpful? I can help create a pull request. Thanks!

**Comment by joto** [comment]
The data that osmcoastline creates is used on https://tools.geofabrik.de/osmi/?view=coastline . There you have a nice interface which makes it easy to find and fix all problems with the coastline.

You should also be able to use the sqlite files to generate any kind of report from it that you like. I don't see the need to change anything in osmcoastline for that. The data is in the sqlite file, it just becomes a question of writing some SQL scripts to display it in any form you like.

**Comment by liyinxiao** [comment]
Thanks for the info. This interface is really cool!
